FinkiSnippets.Web/ViewModels/StartViewModel.cs
using Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace App.ViewModels
{
    public class StartViewModel
    {
        public List<Event> NextEvents { get; set; }
        public List<Event> ActiveEvents { get; set; }
    }
}

FinkiSnippets.Web/Controllers/CodeController.cs
using App.Models;
using App.ViewModels;
using Entity;
using FinkiSnippets.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Utilities;

namespace App.Controllers
{
    [Authorize]
    public class CodeController : Controller
    {
        private ApplicationUserManager _userManager;
        private readonly IUserService _userService;
        private readonly IEventService _eventService;
        private readonly ISnippetService _snippetService;

        public CodeController(IEventService eventService, ISnippetService snippetService, ApplicationUserManager userManager, IUserService userService)
        {
            _eventService = eventService;
            _snippetService = snippetService;
            _userService = userService;
            _userManager = userManager;
        }


        public ActionResult Start()
        {
            List<Event> NextEvents = _eventService.GetNextEvents();
            List<Event> ActiveEvents = _eventService.GetActiveEvents();

            StartViewModel model = new StartViewModel { ActiveEvents = ActiveEvents, NextEvents = NextEvents };
            return View(model);
        }

        public ActionResult Lobby(int id)
        {
            Event ev = _eventService.GetEventById(id);

            //When redirected to this active event present a message
            if (TempData["RedirectToLobbyMsg"] != null)
            {
                ViewBag.msg = "Мора да го завршите активното тестирање пред да започнете ново.";
            }

            return View(ev);
        }

        //id == orderNumber
        public ActionResult Game(int id)
        {
            string userID = User.Identity.GetUserId();
                       
            var userActiveEvent = _userService.UserActiveEvent(userID);
            var validateEvent = _eventService.GetEventById(id);

            //Event doesnt exist , its finished or it is not started yet
            if (validateEvent == null || validateEvent.End < DateHelper.GetCurrentTime() || validateEvent.Start > DateHelper.GetCurrentTime())
            {                
                return RedirectToAction("Start");
            }

            //Has no active events start a new one
            if (userActiveEvent == null)
            {   
                EventSnippets firstSnippet = _userService.BeginEvent(User.Identity.GetUserId(), validateEvent.ID);

                //Already participated and finished
                if (firstSnippet == null)
                {
                    TempData["EventFinished"] = true;
                    return RedirectToAction("Result");
                }
                _snippetService.CreateInitialAnswer(userID, firstSnippet.EventID,firstSnippet.SnippetID);
                userActiveEvent = _userService.UserActiveEvent(userID);
                ViewBag.lastOrderNumber = userActiveEvent.OrderNumber;
                firstSnippet.Event = validateEvent;
                return View(firstSnippet);
                //return view with first snippet
            }
            
            //Has active event but wants to start another one
            if(userActiveEvent.EventID != validateEvent.ID)
            {
                // should redirect to lobby of the event
                TempData["RedirectToLobbyMsg"] = true;
                return RedirectToAction("Lobby", new { id = userActiveEvent.EventID });
            }

            int lastAnsweredOrderNumber = _snippetService.GetLastAnsweredSnippetOrderNumber(userID, userActiveEvent.EventID);
            if(++lastAnsweredOrderNumber > userActiveEvent.OrderNumber)
            {
                _eventService.FinishEventForUser(userActiveEvent.EventID, userID);
                TempData["EventFinished"] = true;
                return RedirectToAction("Result");
            }

            
            var model = _snippetService.GetSnippetWithOrderNumber(lastAnsweredOrderNumber, userActiveEvent.EventID);
            _snippetService.CreateInitialAnswer(userID, userActiveEvent.EventID, model.SnippetID);
            ViewBag.lastOrderNumber = userActiveEvent.OrderNumber;

            model.Event = validateEvent;

            return View(model);
        }

        [HttpPost]
        public ActionResult NextSnippet(int SnippetID, int EventID, string answer)
        {

            string userID = User.Identity.GetUserId();
            bool res = _snippetService.SubmitAnswer(userID, EventID, SnippetID, answer);

            return RedirectToAction("Game", new { id = EventID });
        }

        public ActionResult Result()
        {

            if (TempData["EventFinished"] == null)
                return RedirectToAction("Game", new { id = 0 });

            return View();
        }


    }
}

FinkiSnippets.Web/Views/Code/Game.cshtml
@model Entity.EventSnippets

@{
    ViewBag.Title = "Game";

}

@*<div class="countdown small span4" data-role="countdown" data-stoptimer="@Model.Event.End"></div>*@


<div class="grid">
    <div class="row">
        <div class="span9">
            <ul style="list-style-type:none;margin:0 0 30px 0;padding:0;">
                @for (int i = 1; i <= (int)ViewBag.lastOrderNumber; i++)
                {
                    if (i == Model.OrderNumber)
                    {
                        <li style="display:inline;"><button class="danger mini">@i</button></li>
                    }
                    else
                    {
                        <li style="display:inline;"><button class="mini">@i</button></li>
                    }
                }
            </ul>
        </div>
        <div id="CDT" class="small span3"></div>
    </div>
</div>
<h2 style="margin-bottom:25px;">@Model.Snippet.Question</h2>

<div id="editor">@HttpUtility.UrlDecode(Model.Snippet.Code)</div>


@using(Html.BeginForm("NextSnippet", "Code"))
{
    <br>
    <label>Внесете го одговорот овде:</label>
    <br>
    <input id="output" name="answer" type="text">    
    <input type="text" name="SnippetID" value="@Model.SnippetID" hidden />
    <input type="text" name="EventID" value="@Model.EventID" hidden />

    <div style="padding-top:10px;">
        <button class="button" id="btnClear">Clear</button>
        <input type="submit" value="Next" class="button" />
    </div>
}

@section Scripts{
    <script src="~/Scripts/src-noconflict/ace.js"></script>
    <script src="~/Scripts/metro-times.js"></script>
    <script src="~/Scripts/metro-countdown.js"></script>
    <script>
        $(document).ready(function () {

            $("#btnClear").click(function (event) {
                event.preventDefault();
                $("#output").val("");
            });

            
            var editor = ace.edit("editor");
            editor.setTheme("ace/theme/eclipse");
            editor.getSession().setMode("ace/mode/java");
            editor.setOptions({
                readOnly: true,
                highlightActiveLine: false,
                highlightGutterLine: false
            });
            editor.renderer.$cursorLayer.element.style.opacity = 0;
            var heightUpdateFunction = function () {

                // http://stackoverflow.com/questions/11584061/
                var newHeight =
                          editor.getSession().getScreenLength()
                          * editor.renderer.lineHeight
                          + editor.renderer.scrollBar.getWidth();

                if (newHeight < 100)
                    newHeight = 100;

                $('#editor').height(newHeight.toString() + "px");
                $('#editor-section').height(newHeight.toString() + "px");

                // This call is required for the editor to fix all of
                // its inner structure for adapting to a change in size
                editor.resize();
            };

            
            // Set initial size to match initial content
            heightUpdateFunction();

            // Whenever a change happens inside the ACE editor, update
            // the size again
            editor.getSession().on('change', heightUpdateFunction);                        
        });
    </script>
    <script language="JavaScript" type="text/javascript">
        function CountdownTimer(elm, tl, mes) {
            this.initialize.apply(this, arguments);
        }
        CountdownTimer.prototype = {
            initialize: function (elm, tl, mes) {
                this.elem = document.getElementById(elm);
                this.tl = tl;
                this.mes = mes;
            }, countDown: function () {
                var timer = '';
                var today = new Date();
                var day = Math.floor((this.tl - today) / (24 * 60 * 60 * 1000));
                var hour = Math.floor(((this.tl - today) % (24 * 60 * 60 * 1000)) / (60 * 60 * 1000));
                var min = Math.floor(((this.tl - today) % (24 * 60 * 60 * 1000)) / (60 * 1000)) % 60;
                var sec = Math.floor(((this.tl - today) % (24 * 60 * 60 * 1000)) / 1000) % 60 % 60;
                var milli = Math.floor(((this.tl - today) % (24 * 60 * 60 * 1000)) / 10) % 100;
                var me = this;

                if ((this.tl - today) > 0) {
                    if (day) timer += '<span class="day">' + day + ' : </span>';
                    if (hour) timer += '<span class="hour">' + hour + ' : </span>';
                    timer += '<span class="min">' + this.addZero(min) + ' : </span><span class="sec">' + this.addZero(sec) + '</span>';//<span class="milli">' + this.addZero(milli) + '</span>';
                    this.elem.innerHTML = timer;
                    tid = setTimeout(function () { me.countDown(); }, 10);
                } else {
                    this.elem.innerHTML = this.mes;
                    return;
                }
            }, addZero: function (num) { return ('0' + num).slice(-2); }
        }
        function CDT() {
            var tl = new Date('@Model.Event.End');
            var timer = new CountdownTimer('CDT', tl, 'Времето истече, тестирањето заврши!');
            timer.countDown();
        }
        window.onload = function () {
            CDT();
        }
    </script>
}

FinkiSnippets.Web/Views/Code/Lobby.cshtml
@model Entity.Event

@{
    ViewBag.Title = "Lobby";
}

<h2>@Model.Name</h2>

<hr />

<div class="description">@Html.Raw(Model.Description)</div>

@if (Model.Start > Utilities.DateHelper.GetCurrentTime())
{
    <div class="countdown" data-role="countdown" data-stoptimer="@Model.Start"></div>
}
else
{
    <br />
    <a href="@Url.Action("Game", "Code", new { id = Model.ID })" class="button default large">Започни</a>
}

@section Scripts{
    <script src="~/Scripts/metro-countdown.js"></script>
    <script></script>
    <script>
        $(function () {
           
            var msg = '@ViewBag.msg';

            if (msg) {
                $.Notify({
                    caption: "Статус",
                    content: msg,
                    timeout: 10000,
                    style: { background: "red", color: "#fff" }
                });
            }
        });
    </script>
}

FinkiSnippets.Web/Views/Code/Result.cshtml
@{
    ViewBag.Title = "Result";
}

<h2>Тестирањето заврши</h2>

<a href="@Url.Action("Start", "Code")" class="button default large">Дома</a>

FinkiSnippets.Web/Views/Code/Start.cshtml
@model App.ViewModels.StartViewModel

@{
    ViewBag.Title = "Start";
}


<h2>Активни Натпревари</h2>

<div id="active">
    <table class="table bordered">
        <thead>
            <tr>
                <th class="text-left">Име</th>
                <th class="text-left">Датум</th>
                <th class="text-left">Почеток</th>
                <th class="text-left">Крај</th>
                <th class="text-left"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.ActiveEvents != null && Model.ActiveEvents.Any())
            {
                foreach (var ev in Model.ActiveEvents)
                {
                    <tr class="">
                        <td>@ev.Name</td>
                        <td>@String.Format("{0} / {1} / {2}", ev.Start.Day, ev.Start.Month, ev.Start.Year)</td>
                        <td>@ev.Start.TimeOfDay</td>
                        <td>@ev.End.TimeOfDay</td>
                        <td style="width:40px;"><a href="@Url.Action("Lobby", "Code", new { id=ev.ID })" class="button default small">Лоби</a></td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<h2>Следни Натпревари</h2>

<div id="next">

    <table class="table bordered">
        <thead>
            <tr>
                <th class="text-left">Име</th>
                <th class="text-left">Датум</th>
                <th class="text-left">Почеток</th>
                <th class="text-left">Крај</th>
                <th class="text-left"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.NextEvents != null && Model.NextEvents.Any())
            {
                foreach (var ev in Model.NextEvents)
                {
                    <tr class="selected">
                        <td>@ev.Name</td>
                        <td>@String.Format("{0} / {1} / {2}", ev.Start.Day, ev.Start.Month, ev.Start.Year)</td>
                        <td>@ev.Start.TimeOfDay</td>
                        <td>@ev.End.TimeOfDay</td>
                        <td style="width:40px;"><a href="@Url.Action("Lobby", "Code", new { id=ev.ID })" class="button default small">Лоби</a></td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

FinkiSnippets.Web/Views/Code/Test.cshtml
@{
    ViewBag.Title = "Test";
}

<h2>Test</h2>